Temporal mission draft
CTSRD-CHERI/cheri-exercises pull request #27
Opened 2020-09-12 01:49 UTC by nwf

Here's a start at a mission, but I've run out of creative juices for the evening, I think.  This is a sort of "programmable" farm simulator (hah).

The fundamental bug to be exploited here relies solely on pointer farming, and not a particularly clever or opaque farmer.  On RISC-V with dlmalloc this is trivially exploited; if stochastic temporal defences are deployed, they would have to be overcome (but I don't think we have such an allocator handy); for caprevoke, it shouldn't be possible to construct the alias.
Unfortunately, this example continues to function in CHERI purecap without caprevoke, since the farming gadget is perfect.

I am open to suggestion for how to extend this with a more subtle capability farming gadget; @rwatson's suggestion of using cap-oblivious `memcpy` seems like a useful thing to try.  We should also have a red herring of permitting data injection somewhere, possibly to the same buffers being memcpy'd?  Bonus points if some data clobbering is required to trigger the farming gadget later.

2020-09-12 10:55 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +	exit(0);
If only this were GNU/Hurd, then we could exit with EIEIO.

2020-09-12 10:59 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +		switch(c) {
```suggestion
		switch (c) {
```

2020-09-12 11:13 UTC, nwf commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +	exit(0);
For maximal confusion, one day I hope to see HURD running on POWER.

2020-09-12 17:05 UTC, nwf commented
Revised edition, now with a UFO that can abduct pointers and make crop signs.  Probably still merits some tweaking, and I'm sure that I've left some development artefacts in place.  But still, progress?

2020-09-17 20:01 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/README.md
> +exploitable* (though in fewer ways) on CHERI-RISC-V without a temporally safe
```suggestion
exploitable* (though in fewer ways) on CHERI-RISC-V without a temporally-safe
```

2020-09-17 20:02 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/README.md
> +heap allocator.
Do we want to be so explicit, or do we want to let researchers discover this for themselves?

2020-09-17 20:03 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/README.md
> +of `0`. Ordinary termination is signaled with `1` and invalid input results in
Unless they inject a pointer to `exit(3)`...

2020-09-17 20:06 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/README.md
> +* CHERI-RISC-V with temporal safety: `./ccc riscv64-purecap -DCAPREVOKE`
We don't bother with these elsewhere. I'd just document that `-DCAPREVOKE` is needed if and only if you want temporal safety, as is done in the first mission. But I would at least drop the `./` from `./ccc` since that's specific to a user's setup, and they might wish to run it as `/path/to/exercises/tools/ccc` instead.

2020-09-17 20:07 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/README.md
> +  collection.
This needs to clarify how this relates to the cursor.

2020-09-17 20:10 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +	void	(* volatile describe)(struct crop *);
I would imagine this code is sufficiently obfuscated with regards to UB that the `volatile` is unnecessary?

2020-09-17 20:10 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +  "Structure size mismatch");
```suggestion
_Static_assert(sizeof(struct crop) == sizeof(struct farm),
    "Structure size mismatch");
```

2020-09-17 20:11 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +  "Structure size mismatch");
```suggestion
_Static_assert(sizeof(struct crop) == sizeof(union ufo),
    "Structure size mismatch");
```

2020-09-17 20:12 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +	char buf[sizeof(struct crop)];
```suggestion
	void	*ptrA;
	char	buf[sizeof(struct crop)];
```

2020-09-17 21:12 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +#elif __CHERI_PURE_CAPABILITY__
Missing `defined(...)`

2020-09-17 21:13 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +	while((c = getchar()) != EOF) {
```suggestion
	while ((c = getchar()) != EOF) {
```

2020-09-17 22:31 UTC, nwf commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +#elif __CHERI_PURE_CAPABILITY__
Yes, and, while thinking about preprocessor defines, I've made caprevoke the default and flipped to a `-DNO_CAPREVOKE` if you don't want it.

2020-09-17 22:47 UTC, nwf commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +#elif __CHERI_PURE_CAPABILITY__
Indeed.  While here, I've just dropped `defined(CAPREVOKE)` everywhere.

2020-09-17 23:32 UTC, nwf commented on src/missions/use-after-free-control-flow/README.md
> +heap allocator.
Replaced with alternate wording, keeping the last bit.

2020-09-17 23:32 UTC, nwf commented on src/missions/use-after-free-control-flow/README.md
> +  collection.
Done, I think.

2020-09-17 23:32 UTC, nwf commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +	void	(* volatile describe)(struct crop *);
Yea, it results in the same code with and without, so it's gone.

2020-09-18 00:21 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +	if(getenv("MALLOC_DISABLE_REVOCATION") == NULL) {
```suggestion
	if (getenv("MALLOC_DISABLE_REVOCATION") == NULL) {
```

2020-09-18 00:21 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +		c->describe = (cid & 1) ? descr_1 : descr_2 ;
This is now entirely artificial. I preferred it when the function itself had the crop type in it, as that's more reminiscent of the classic OO interface + override examples you see (Animal interface has speak method, Dog implements that as printing bark, Cat implements that as printing meow).

2020-09-18 00:21 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +	/* Program startup in GDB is not the most celeritous thing */
What's this got to do with getenv and fprintf?

2020-09-18 00:22 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +				farmp[fix]);
```suggestion
			    farmp[fix]);
```

2020-09-18 00:22 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +					f->cursor);
```suggestion
				    f->cursor);
```

2020-09-18 00:22 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +					f->cursor->describe);
```suggestion
				    f->cursor->describe);
```

2020-09-18 00:23 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +							farm_cropq);
```suggestion
					    farm_cropq);
```

2020-09-18 00:23 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +							cropq);
```suggestion
					    cropq);
```

2020-09-18 00:24 UTC, jrtc27 commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +							farm_cropq);
```suggestion
					    farm_cropq);
```

2020-09-18 01:43 UTC, nwf commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +		c->describe = (cid & 1) ? descr_1 : descr_2 ;
That's fair; I'll put it back.

2020-09-18 01:44 UTC, nwf commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +	/* Program startup in GDB is not the most celeritous thing */
It's the reason for the banner in the first place.

2020-09-18 16:57 UTC, brooksdavis approved these changes
A couple minor whitespace nits, but otherwise looks ready to go.

2020-09-18 16:57 UTC, brooksdavis commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +  "Structure size mismatch");
```suggestion
    "Structure size mismatch");
```

2020-09-18 16:57 UTC, brooksdavis commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +  "Structure size mismatch");
```suggestion
    "Structure size mismatch");
```

2020-09-18 17:10 UTC, brooksdavis commented on src/missions/use-after-free-control-flow/temporal-mission.c
> +#endif
```suggestion
		case '!':
#if defined(__CHERI_PURE_CAPABILITY__)
			malloc_revoke();
#endif
			break;
```
I wonder if this would be friendlier.

2020-09-18 19:09 UTC, jrtc27 requested changes
You need to actually `{{#include ...}}` the C source file in the Markdown.

2020-09-18 20:30 UTC, brooksdavis commented
Merged manually with a small addition.

2020-09-18 20:30 UTC, closed without merging